### ISSUE TITLE
Only loads to 78%

### ISSUE THREAD

**Issue by 2braincells2go** [jeroenverfallie/ggo13-transcube#27]
Love this game:)

We set it up so others can play on a school network. Really to improve hand / eye coordination for disabled students.

Issue having is on chrome (students forced to use...) it loads many time to only 78%. If on android tablet it always loads to 78% and does not finish.

Anything you can think of to prevent this from happening?

BTW: no errors or shown in browser developer error consoles, so no help there.

Many thanks!

**Comment by jeroenverfallie** [comment]
Hi,

I'm very sorry I didn't see any notification or mail coming in about this issue.
I'm pleased to hear you love it and use it in your school for disabled students, that's great!

This most likely is overdue, but if you still want to solve the issue, here's some possibilities:

You say you set it up to make it work on the school network, so I take it you cloned the repo and set it up localy? If so, are you using the latest version? 

I [did a fix](https://github.com/jeroenverfallie/ggo13-transcube/commit/8e1d1ec1bc3979daf9f82a76eeed0717595ec5a7) for the loader issues on the 24th of 2013, so I'm guessing you should have at least that version. If not, consider updating.

If this is not overdue and you are still facing issues, please respond and I'll get back to you ASAP, I'll more closely monitor the issues on this repo!

**Comment by ypling** [comment]
Having this problem on Mac Safari, Chrome and firefox stuck at 75% every time.

**Comment by 2braincells2go** [comment]
I never got it to work and actually forgot about after so much time passed. Will have to try it again after weekend.

**Comment by gengzang** [comment]
你好吗
