### ISSUE TITLE
Level 8 The Way Around is impossible to be solved

### ISSUE THREAD

**Issue by ifaniqbal** [jeroenverfallie/ggo13-transcube#28]

**Comment by amritkrs** [comment]
Its not!
Try again.

**Comment by jeroenverfallie** [comment]
I have no idea why I didn't catch any notification of this issue, but, for what it's worth:

It is not, indeed :) -- The levels always introduce new solutions, and then recap on those. Level 8 requires a solution your learn in Level 3, Level 7 and Level 6 combined, with a slightly more tricky setup.

Sorry I didn't respond any earlier.

**Comment by testitem** [comment]
Is there any hints? I couldn't make head or tail out of it.
